### ISSUE TITLE
Can we get a callback ?

### ISSUE THREAD

**Issue by ZARk-be** [Wruczek/Bootstrap-Cookie-Alert#10]
Can we get a callback function ?

Technically, we are supposed to not use ANY cookies until the user has given consent.
Therefore i need to know when the user clicked on AGREE to load Analytics and other tracking cookies.

**Comment by derek-baker** [comment]
@ZARk-be  Couldn't you just add a click listener to the markup?

**Comment by Wruczek** [comment]
Added in 1.2.0

```js
window.addEventListener("cookieAlertAccept", function() {
    alert("cookies accepted")
})
```
