### ISSUE TITLE
Make cookie alert remember close action

### ISSUE THREAD

**Issue by annban** [Wruczek/Bootstrap-Cookie-Alert#18]
Thank you for sharing your work, much helpful! I was wondering if there's an easy way to configure the alert so that it remembers that a user has already accepted (closed) the alert. If I'm right currently the alert is triggered on each site load.

**Comment by Wruczek** [comment]
Hello, currently the alert is remembering the consent with a cookie.

**Comment by annban** [comment]
Oh this is fantastic! When I tested it locally it was firing on each site load (possibly because of the test environment?).

**Comment by Wruczek** [comment]
Test it here: https://wruczek.github.io/Bootstrap-Cookie-Alert/demo
