### ISSUE TITLE
Dependencies

### ISSUE THREAD

**Issue by AndiLeni** [Wruczek/Bootstrap-Cookie-Alert#2]
Hello,
I wanted to ask what the'cookiealert-dependencies.js' file is for. 
The benefits are not yet quite clear to me :)

Regards
Andi

**Comment by Wruczek** [comment]
You should use `cookiealert-standalone.js` in 99% of the use cases.

If it so happens that you already have jQuery and jsCookie included in your project, you can use the `dependencies` version. The code is smaller and a little more clean. Other than that - there is no difference between them - **they both do exactly the same**

**Comment by AndiLeni** [comment]
Thanks for clarifying.
I would put this explanation in the readme file for other users.
