### ISSUE TITLE
Feature request: Semi-standalone version?

### ISSUE THREAD

**Issue by LarsGMortensen** [Wruczek/Bootstrap-Cookie-Alert#5]
Most sites (at least most of my sites) already have jQuery implemented for various other functionality. But they don't have jsCookie.

Would it be possible to make a semi-standalone-version that is dependent on jQuery, but is standalone in regards to jsCookie ...?

Thanks a lot!

**Comment by AndiLeni** [comment]
In the repository is already a standalone version that does not rely on jscookie.

**Comment by Wruczek** [comment]
Actually, I was thinking about removing the dependency version all together and leaving just the vanilla implementation. We use so little jQuery in the dependency version that it doesn't benefit us in any real way, and having 2 separate scripts doing the same is (I feel like) not needed at this point. + it creates confusion (#2)

I think that having just the vanilla version + vanilla minified would be the best option.

**Comment by ghost** [comment]
@Wruczek I'd remove the dependency version, it's 700B smaller than the vanilla implementation.

**Comment by Wruczek** [comment]
Yep I think that's a good move. I will push an update and remove the dependency version.
