### ISSUE TITLE
Alert doesn't show up in Safari

### ISSUE THREAD

**Issue by khannurien** [Wruczek/Bootstrap-Cookie-Alert#8]
Hi, thanks a lot for this tool!
I'm using it alongside Bootstrap 3 and AdminLTE 2.

While it does work with Firefox and Chrome, the alert does not show up in Safari (12.1).
The demo does not work either.

Is there any way I could help you with debugging?

**Comment by Wruczek** [comment]
I don't have a mac, so unfortunately I can't check it myself.
But you can open the developer console, and check if there are any error. If none, then go to the DOM inspector and try to find the cookie alert, then see in CSS attributes why its not showing up.

**Comment by khannurien** [comment]
No error show up in the console, however I did find a "hidden" attribute to the nodes:

<img width="797" alt="Capture d’écran 2019-07-31 à 09 53 25" src="https://user-images.githubusercontent.com/31770422/62193943-21250600-b379-11e9-995f-a273076d43c1.png">

I'm willing to help you investigate further, don't hesitate to give me directions :-)

**Comment by Wruczek** [comment]
So I've tested it with a website testing tool on Safari 12.0 and its working.
Can you make sure that it's not something with your browser? Try disabling your addons and ad-blockers and visit the demo website in incognito/private mode.

![image](https://user-images.githubusercontent.com/7156344/62414966-d201fe00-b622-11e9-9ae0-964983f4692b.png)
